// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdxFeNBUiO97EG_SQd8V7s3tWD0FfkWO8',
    appId: '1:310855518156:web:1826304aabb55a05f87f69',
    messagingSenderId: '310855518156',
    projectId: 'flash-chat-a4ae2',
    authDomain: 'flash-chat-a4ae2.firebaseapp.com',
    storageBucket: 'flash-chat-a4ae2.appspot.com',
    measurementId: 'G-T7HC60T34H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4X4vRj7IGRBfhxLFkipVEO0a9AQFVcc8',
    appId: '1:310855518156:android:9ee126d21b96b62cf87f69',
    messagingSenderId: '310855518156',
    projectId: 'flash-chat-a4ae2',
    storageBucket: 'flash-chat-a4ae2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdmH3tn_de-HsSxDI2a37uSrzsKDkuZGc',
    appId: '1:310855518156:ios:7c5534d1f0fac0fbf87f69',
    messagingSenderId: '310855518156',
    projectId: 'flash-chat-a4ae2',
    storageBucket: 'flash-chat-a4ae2.appspot.com',
    iosClientId: '310855518156-0snkck41bbtnn5cm7p7jpsc2f6qt274l.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdmH3tn_de-HsSxDI2a37uSrzsKDkuZGc',
    appId: '1:310855518156:ios:7c5534d1f0fac0fbf87f69',
    messagingSenderId: '310855518156',
    projectId: 'flash-chat-a4ae2',
    storageBucket: 'flash-chat-a4ae2.appspot.com',
    iosClientId: '310855518156-0snkck41bbtnn5cm7p7jpsc2f6qt274l.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChat',
  );
}
